package com.bank.epricing.controller;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.info.BuildProperties;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.sql.DataSource;
import java.sql.Connection;
import java.time.LocalDateTime;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * ╔══════════════════════════════════════════════════════════════════════════╗
 * ║  HealthController.java — Custom Health and Info Endpoints               ║
 * ╠══════════════════════════════════════════════════════════════════════════╣
 * ║  WHY THIS EXISTS ALONGSIDE /actuator/health:                            ║
 * ║  /actuator/health: Spring Boot's automatic health endpoint.            ║
 * ║    - Checks: DB connectivity, disk space, custom HealthIndicators      ║
 * ║    - Returns: {"status": "UP"} or {"status": "DOWN"}                   ║
 * ║    - Lives on port 8081 (management port)                              ║
 * ║                                                                          ║
 * ║  /api/v1/health: Our custom health endpoint on the MAIN port (8080).   ║
 * ║    - Can be called by clients, load balancers, Kubernetes probes       ║
 * ║    - Returns richer business context                                    ║
 * ║    - Shows which version is deployed (from build-info.properties)      ║
 * ║                                                                          ║
 * ║  In Kubernetes: This endpoint is used for liveness probes.             ║
 * ║    livenessProbe:                                                       ║
 * ║      httpGet:                                                           ║
 * ║        path: /api/v1/health                                             ║
 * ║        port: 8080                                                       ║
 * ╚══════════════════════════════════════════════════════════════════════════╝
 */
@RestController
@RequestMapping("/health")
public class HealthController {

    private static final Logger log = LoggerFactory.getLogger(HealthController.class);

    private final DataSource dataSource;
    private final BuildProperties buildProperties;

    public HealthController(DataSource dataSource,
                            @org.springframework.beans.factory.annotation.Autowired(required = false)
                            BuildProperties buildProperties) {
        this.dataSource = dataSource;
        this.buildProperties = buildProperties;
    }

    /**
     * GET /api/v1/health
     * Returns application health with database connectivity check.
     */
    @GetMapping
    public ResponseEntity<Map<String, Object>> health() {
        Map<String, Object> health = new LinkedHashMap<>();
        health.put("status", "UP");
        health.put("service", "epricing-service");
        // Version read from build-info.properties generated by spring-boot:build-info Maven goal.
        // Auto-updates when pom.xml <version> changes — no manual editing needed.
        health.put("version", buildProperties != null ? buildProperties.getVersion() : "unknown");
        health.put("timestamp", LocalDateTime.now().toString());

        // Database connectivity check
        Map<String, String> db = new LinkedHashMap<>();
        try (Connection conn = dataSource.getConnection()) {
            db.put("status", "UP");
            db.put("product", conn.getMetaData().getDatabaseProductName());
            db.put("version", conn.getMetaData().getDatabaseProductVersion());
        } catch (Exception e) {
            log.error("Database health check failed | error={}", e.getMessage());
            db.put("status", "DOWN");
            db.put("error", e.getMessage());
            health.put("status", "DEGRADED");
        }
        health.put("database", db);

        Map<String, Object> jvm = new LinkedHashMap<>();
        Runtime rt = Runtime.getRuntime();
        long usedMemory = (rt.totalMemory() - rt.freeMemory()) / 1024 / 1024;
        long maxMemory = rt.maxMemory() / 1024 / 1024;
        jvm.put("heapUsedMb", usedMemory);
        jvm.put("heapMaxMb", maxMemory);
        jvm.put("heapUtilizationPct", String.format("%.1f%%", (double) usedMemory / maxMemory * 100));
        jvm.put("processors", rt.availableProcessors());
        health.put("jvm", jvm);

        health.put("endpoints", Map.of(
            "actuator", "http://localhost:8081/actuator",
            "prometheus", "http://localhost:8081/actuator/prometheus",
            "grafana", "http://localhost:3000",
            "yugabytedb_ui", "http://localhost:15433"
        ));

        log.info("Health check completed | status={}", health.get("status"));
        return ResponseEntity.ok(health);
    }
}
